- name: Copiar preseed.cfg
  copy:
    src: preseed.cfg
    dest: "{{ wrk_dir }}/preseed.cfg"
    mode: "0644"
  become: true

- name: Copiar authorized_keys si existe
  copy:
    src: "{{ ssh_authorized_keys }}"
    dest: "{{ wrk_dir }}/authorized_keys"
    mode: "0644"
  ignore_errors: true

- name: Configurar ISOLINUX
  copy:
    src: isolinux.cfg
    dest: "{{ wrk_dir }}/isolinux/isolinux.cfg"

- name: Configurar txt.cfg
  copy:
    src: txt.cfg
    dest: "{{ wrk_dir }}/isolinux/txt.cfg"

- name: Configurar GRUB (UEFI)
  copy:
    src: grub.cfg
    dest: "{{ wrk_dir }}/boot/grub/grub.cfg"
