- name: instalar openssh-server
  ansible.builtin.apt:
    name:
      - openssh-server
      - bridge-utils
      - cpu-checker
      - libvirt-clients
      - libvirt-daemon
      - qemu-system
      - qemu-system-x86
      - qemu-utils
      - virtinst
      - virt-manager
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - qemu-system
    state: present
    update_cache: yes
  become: true

- name: asegurar que el servicio ssh este iniciado y habilitado
  ansible.builtin.systemd_service:
    name: ssh
    state: started
    enabled: yes
  become: true
