- name: Guardar la configuración del cluster en el host que operará el cluster
  ansible.builtin.copy:
    dest: "{{home_dir}}/.kube/config"
    content: "{{ hostvars['k8s-master'].microk8s_config_content }}"
    mode: "0600"
    owner: "{{user_host}}"
    group: "{{user_host}}"
  delegate_to: "{{ item }}"
  loop: "{{ groups['local'] }}"
