vm_list:
  - name: k8s-master
    memory: 2096
    cpus: 2
    disk_size: 22
    mac1: 08:00:57:67:62:d6
    mac2: 0800272762D6

  - name: k8s-worker
    memory: 2096
    cpus: 1
    disk_size: 22
    mac1: 08:00:27:23:55:d8
    mac2: 0800272754D8
